import { NextRequest, NextResponse } from 'next/server'
import { GoogleGenAI } from '@google/genai'

const GOOGLE_GENERATIVE_AI_API_KEY = process.env.GOOGLE_GENERATIVE_AI_API_KEY

if (!GOOGLE_GENERATIVE_AI_API_KEY) {
  console.error('Missing GOOGLE_GENERATIVE_AI_API_KEY environment variable')
}

export async function POST(request: NextRequest) {
  try {
    if (!GOOGLE_GENERATIVE_AI_API_KEY) {
      return NextResponse.json(
        { success: false, error: 'AI service not configured' },
        { status: 500 }
      )
    }

    const body = await request.json()
    const { dayName, weekNumber, lessons } = body

    // Create a concise prompt for short, clean summaries
    const enhancedPrompt = `Bạn là trợ lý AI tạo tóm tắt phản hồi học tập ngắn gọn cho phụ huynh.

YÊU CẦU:
- Chỉ viết 3-5 câu ngắn gọn
- Không sử dụng ký tự đặc biệt như **, ##, emoji
- Không viết in hoa
- Tập trung vào điểm mạnh và gợi ý cải thiện
- Ngôn ngữ tích cực, phù hợp với phụ huynh

DỮ LIỆU PHẢN HỒI NGÀY ${dayName}, TUẦN ${weekNumber}:
${lessons.map((lesson: { period: number; subject_name: string; teacher_name: string; feedback?: string }) => `
${lesson.subject_name}: ${lesson.feedback || 'Chưa có phản hồi'}
`).join('\n')}

Hãy tạo tóm tắt ngắn gọn, rõ ràng về tình hình học tập trong ngày.`

    // Initialize Google Gemini AI
    const ai = new GoogleGenAI({
      apiKey: GOOGLE_GENERATIVE_AI_API_KEY
    })

    // Generate content using Gemini
    const result = await ai.models.generateContent({
      model: 'gemini-2.0-flash-001',
      contents: enhancedPrompt,
      config: {
        temperature: 0.7,
        maxOutputTokens: 2048,
        topP: 0.8,
        topK: 40
      }
    })

    if (!result?.text) {
      throw new Error('No text generated by AI')
    }

    const aiSummary = result.text

    return NextResponse.json({
      success: true,
      summary: aiSummary,
      isAIGenerated: true
    })

  } catch (error) {
    console.error('AI daily summary generation error:', error)
    
    return NextResponse.json(
      { 
        success: false, 
        error: error instanceof Error ? error.message : 'Failed to generate AI summary'
      },
      { status: 500 }
    )
  }
}
